# Generated by Django 3.2.8 on 2021-10-28 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_insec.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 28, 16, 56, 36, 201044))),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_insec.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_insec.user')),
            ],
        ),
    ]
