# Generated by Django 3.2.8 on 2021-11-07 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insec', '0002_auto_20211030_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 11, 55, 35, 892738)),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
